### ISSUE TITLE
Ability to use -chdir=DIR with tf validate and tf fmt

### ISSUE THREAD

**Issue by lexicalunit** [gruntwork-io/pre-commit#106]
**Describe the solution you'd like**
I need to be able to set the dir via the global terraform argument `-chdir=...` before running validate:

```yaml
repos:
- repo: https://github.com/gruntwork-io/pre-commit
  rev: v0.1.23
  hooks:
      - id: terraform-validate
        args: [-chdir=whatever]
```

However, what the above configuration actually does is attempt to pass `-chidr=whatever` to the validate subcommand. In other words, it executes this:

```shell
terraform validate -chdir=whatever
```

But that's an error because `-chdir` is not a valid argument for `terraform validate`.

What I need is a way to execute this:

```shell
terraform -chdir=whatever validate
```

**Describe alternatives you've considered**
I haven't found a way to set the working directory via some other means.

**Comment by lexicalunit** [comment]
A workaround I found was to do use the `entry` option and passing a short script to `/bin/sh`.
```yaml
repos:
- repo: https://github.com/gruntwork-io/pre-commit
  rev: v0.1.23
  hooks:
      - id: terraform-validate
        name: terraform validate
        entry: /bin/sh -c 'cd /path/to/dir && terraform validate'
```
