### ISSUE TITLE
Add `terragrunt-providers-lock` hook

### ISSUE THREAD

**Issue by Tensho** [gruntwork-io/pre-commit#111]
**Describe the solution you'd like**

It would be nice to have a hook which locks versions in `.terraform.lock.hcl` file automatically.

### How could pre-commit-terraform help solve your problem?

Introduce `terragrunt-providers-lock` hook which runs `terragrunt providers lock` command.

**Describe alternatives you've considered**

Write a local hook, something like:
```yaml
  - repo: local
    hooks:
      - id: terragrunt-providers-lock
        name: Terragrunt providers lock
        entry: terragrunt providers lock -platform=darwin_amd64 -platform=darwin_arm64 -platform=linux_amd64
        language: script
        files: '\.hcl$'
```

**Additional context**

A similar `terraform_providers_lock` hook for Terraform is provided by [pre-commit-terraform](https://github.com/antonbabenko/pre-commit-terraform?tab=readme-ov-file#terraform_providers_lock) project.
