### ISSUE TITLE
Failure during terragrunt call : fork/exec /opt/homebrew/bin/tenv: operation not supported by device

### ISSUE THREAD

**Issue by madchap** [gruntwork-io/pre-commit#120]
Hi,

**Describe the bug**
Installed terragrunt-hclfmt as:

```
-   repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.25 # Get the latest from: https://github.com/gruntwork-io/pre-commit/releases
    hooks:
      - id: terragrunt-hclfmt
```

which leads to:
```
Terragrunt hclfmt........................................................Failed
- hook id: terragrunt-hclfmt
- exit code: 1

Failure during terragrunt call : fork/exec /opt/homebrew/bin/tenv: operation not supported by device
Failure during terragrunt call : fork/exec /opt/homebrew/bin/tenv: operation not supported by device
```

**To Reproduce**
Just install terragrunt with `tenv` I guess and trigger pre-commit.

**Expected behavior**
It performs its operations.

`tg hclfmt` works fine when invoked from the command line.

**Additional context**
Running on Macbook Pro M4.

```
$ tg --version
terragrunt version v0.69.1
```
