### ISSUE TITLE
Sentinel Fmt Hook Does Not Work

### ISSUE THREAD

**Issue by schultzwc18** [gruntwork-io/pre-commit#121]
**Describe the bug**
Hook fails to run when installed through pre-commit because of two bugs:
1. Line 1 must have shebang but is instead on line 2
2. `sentinel fmt` does not have a `diff` command-line argument

**To Reproduce**
Steps to reproduce the behavior including the relevant Terraform/Terragrunt/Packer version number and any code snippets and module inputs you used.

.pre-commit-config.yaml
```yaml
repos:
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.25
    hooks:
      - id: sentinel-fmt
```

```bash
pre-commit install
pre-commit run --all-files
```

**Expected behavior**
Pre-commit hook would run and indicate files requiring formatting

**Nice to have**
- [ ] Terminal output
- [ ] Screenshots

**Additional context**
